import type { RoutineEntry, ExamEntry } from "./types"

export const mockRoutineData: RoutineEntry[] = [
  // 63rd Batch Section A - Based on the provided image
  {
    id: "63a-1",
    courseName: "Electrical Engineering",
    courseCode: "EEE 2204",
    faculty: "TBA",
    room: "Ro-112",
    day: "Saturday",
    startTime: "09:00",
    endTime: "10:25",
    department: "EEE",
    subject: "Electrical Engineering",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-2",
    courseName: "Mathematics",
    courseCode: "MATH 2207",
    faculty: "TBA",
    room: "Ro-117",
    day: "Saturday",
    startTime: "10:30",
    endTime: "11:45",
    department: "Mathematics",
    subject: "Mathematics",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-3",
    courseName: "Computer Science",
    courseCode: "CSE 2213",
    faculty: "MH",
    room: "Ro-136",
    day: "Saturday",
    startTime: "11:50",
    endTime: "13:10",
    department: "CSE",
    subject: "Computer Science",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-4",
    courseName: "Computer Science",
    courseCode: "CSE 2217",
    faculty: "SS",
    room: "Ro-223",
    day: "Saturday",
    startTime: "13:30",
    endTime: "14:50",
    department: "CSE",
    subject: "Computer Science",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-5",
    courseName: "Electrical Engineering",
    courseCode: "EEE 2203",
    faculty: "TBA",
    room: "Ro-134",
    day: "Sunday",
    startTime: "09:00",
    endTime: "10:25",
    department: "EEE",
    subject: "Electrical Engineering",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-6",
    courseName: "Computer Science",
    courseCode: "CSE 2215",
    faculty: "MFB",
    room: "Ro-134",
    day: "Sunday",
    startTime: "10:30",
    endTime: "11:45",
    department: "CSE",
    subject: "Computer Science",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-7",
    courseName: "Computer Science",
    courseCode: "CSE 2214",
    faculty: "MH",
    room: "Ro-213",
    day: "Monday",
    startTime: "09:00",
    endTime: "10:25",
    department: "CSE",
    subject: "Computer Science",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-8",
    courseName: "Mathematics",
    courseCode: "MATH 2207",
    faculty: "TBA",
    room: "Ro-117",
    day: "Monday",
    startTime: "10:30",
    endTime: "11:45",
    department: "Mathematics",
    subject: "Mathematics",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-9",
    courseName: "Computer Science",
    courseCode: "CSE 2213",
    faculty: "MH",
    room: "Ro-136",
    day: "Monday",
    startTime: "11:50",
    endTime: "13:10",
    department: "CSE",
    subject: "Computer Science",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-10",
    courseName: "Computer Science",
    courseCode: "CSE 2217",
    faculty: "SS",
    room: "Ro-223",
    day: "Monday",
    startTime: "13:30",
    endTime: "14:50",
    department: "CSE",
    subject: "Computer Science",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-11",
    courseName: "Electrical Engineering",
    courseCode: "EEE 2203",
    faculty: "TBA",
    room: "Ro-134",
    day: "Tuesday",
    startTime: "09:00",
    endTime: "10:25",
    department: "EEE",
    subject: "Electrical Engineering",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-12",
    courseName: "Computer Science",
    courseCode: "CSE 2215",
    faculty: "MFB",
    room: "Ro-134",
    day: "Tuesday",
    startTime: "10:30",
    endTime: "11:45",
    department: "CSE",
    subject: "Computer Science",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "63a-13",
    courseName: "Computer Science",
    courseCode: "CSE 2216",
    faculty: "MFB",
    room: "Ro-212",
    day: "Tuesday",
    startTime: "13:30",
    endTime: "14:50",
    department: "CSE",
    subject: "Computer Science",
    semester: "Spring 2024",
    batch: "63rd Batch",
    section: "Section A",
    year: "2nd Year",
  },

  // Other batches and sections (keeping some existing data for variety)
  {
    id: "60a-1",
    courseName: "Data Structures and Algorithms",
    courseCode: "CSE-201",
    faculty: "Dr. Sarah Johnson",
    room: "Room 301",
    day: "Saturday",
    startTime: "09:00",
    endTime: "10:25",
    department: "CSE",
    subject: "Data Structures",
    semester: "Spring 2024",
    batch: "60th Batch",
    section: "Section A",
    year: "2nd Year",
  },
  {
    id: "61b-1",
    courseName: "Object Oriented Programming",
    courseCode: "CSE-102",
    faculty: "Prof. Michael Chen",
    room: "Lab 201",
    day: "Saturday",
    startTime: "09:00",
    endTime: "10:25",
    department: "CSE",
    subject: "Programming",
    semester: "Spring 2024",
    batch: "61st Batch",
    section: "Section B",
    year: "1st Year",
  },
  {
    id: "62a-1",
    courseName: "Business Management",
    courseCode: "BBA-101",
    faculty: "Prof. Lisa Thompson",
    room: "Room 401",
    day: "Monday",
    startTime: "11:50",
    endTime: "13:10",
    department: "BBA",
    subject: "Management",
    semester: "Spring 2024",
    batch: "62nd Batch",
    section: "Section A",
    year: "1st Year",
  },
  {
    id: "64a-1",
    courseName: "Advanced Programming",
    courseCode: "CSE-303",
    faculty: "Prof. Alex Turner",
    room: "Lab 205",
    day: "Monday",
    startTime: "09:00",
    endTime: "10:25",
    department: "CSE",
    subject: "Programming",
    semester: "Spring 2024",
    batch: "64th Batch",
    section: "Section A",
    year: "1st Year",
  },
]

export const mockExamData: ExamEntry[] = [
  {
    id: "e1",
    courseName: "Electrical Engineering",
    courseCode: "EEE 2204",
    date: "2024-03-15",
    startTime: "09:00",
    endTime: "12:00",
    room: "Exam Hall A",
    department: "EEE",
    type: "Mid-term",
  },
  {
    id: "e2",
    courseName: "Computer Science",
    courseCode: "CSE 2213",
    date: "2024-03-18",
    startTime: "14:00",
    endTime: "17:00",
    room: "Exam Hall B",
    department: "CSE",
    type: "Mid-term",
  },
  {
    id: "e3",
    courseName: "Mathematics",
    courseCode: "MATH 2207",
    date: "2024-03-20",
    startTime: "09:00",
    endTime: "12:00",
    room: "Exam Hall C",
    department: "Mathematics",
    type: "Mid-term",
  },
  {
    id: "e4",
    courseName: "Business Management",
    courseCode: "BBA-101",
    date: "2024-03-22",
    startTime: "14:00",
    endTime: "17:00",
    room: "Exam Hall A",
    department: "BBA",
    type: "Mid-term",
  },
  {
    id: "e5",
    courseName: "Electrical Engineering",
    courseCode: "EEE 2204",
    date: "2024-05-10",
    startTime: "09:00",
    endTime: "12:00",
    room: "Exam Hall A",
    department: "EEE",
    type: "Final",
  },
  {
    id: "e6",
    courseName: "Computer Science",
    courseCode: "CSE 2213",
    date: "2024-05-13",
    startTime: "14:00",
    endTime: "17:00",
    room: "Exam Hall B",
    department: "CSE",
    type: "Final",
  },
]
